version: '3.5'

services:

  shard1a:
    build: .
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1
      - INIT_SHARD_NODES=shard1a,shard1b,shard1c

  shard1b:
    build: .
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1

  shard1c:
    build: .
    image: stutzlab/mongo-cluster-shard
    environment:
      - SHARD_REPLICA_SET=shard1

  # shard1d:
  #   build: .
  #   image: stutzlab/mongo-cluster-shard
  #   environment:
  #     - SHARD_REPLICA_SET=shard1
    